cc_library(
  name = "biz",
  srcs = [
    "biz.cc"
  ],
  deps = [],
)

cc_test(
  name = "biz_test",
  srcs = [
    "biz_test.cc",
    "biz.cc"
  ],
  deps = [
    "#gmock_main"
  ],
  defs = [
    "USER_TEST"
  ]
)
