// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

#include "profile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_profile_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_profile_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CatProfile;
}  // namespace protobuf_profile_2eproto
namespace qqnews {
class CatProfileDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CatProfile>
      _instance;
} _CatProfile_default_instance_;
class KBUserInfoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<KBUserInfo>
      _instance;
} _KBUserInfo_default_instance_;
}  // namespace qqnews
namespace protobuf_profile_2eproto {
static void InitDefaultsCatProfile() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::qqnews::_CatProfile_default_instance_;
    new (ptr) ::qqnews::CatProfile();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::qqnews::CatProfile::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CatProfile =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCatProfile}, {}};

static void InitDefaultsKBUserInfo() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::qqnews::_KBUserInfo_default_instance_;
    new (ptr) ::qqnews::KBUserInfo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::qqnews::KBUserInfo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_KBUserInfo =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsKBUserInfo}, {
      &protobuf_profile_2eproto::scc_info_CatProfile.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CatProfile.base);
  ::google::protobuf::internal::InitSCC(&scc_info_KBUserInfo.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, lv1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, lv2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, lv3_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::CatProfile, lv4_),
  0,
  1,
  2,
  3,
  4,
  5,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::KBUserInfo, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::KBUserInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qqnews::KBUserInfo, cat_profile_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 11, sizeof(::qqnews::CatProfile)},
  { 17, 23, sizeof(::qqnews::KBUserInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::qqnews::_CatProfile_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::qqnews::_KBUserInfo_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "profile.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rprofile.proto\022\006qqnews\"^\n\nCatProfile\022\014\n"
      "\004type\030\001 \001(\t\022\016\n\006weight\030\002 \001(\t\022\013\n\003lv1\030\003 \001(\t"
      "\022\013\n\003lv2\030\004 \001(\t\022\013\n\003lv3\030\005 \001(\t\022\013\n\003lv4\030\006 \001(\t\""
      "5\n\nKBUserInfo\022\'\n\013cat_profile\030\001 \003(\0132\022.qqn"
      "ews.CatProfile"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 174);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "profile.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_profile_2eproto
namespace qqnews {

// ===================================================================

void CatProfile::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CatProfile::kTypeFieldNumber;
const int CatProfile::kWeightFieldNumber;
const int CatProfile::kLv1FieldNumber;
const int CatProfile::kLv2FieldNumber;
const int CatProfile::kLv3FieldNumber;
const int CatProfile::kLv4FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CatProfile::CatProfile()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_profile_2eproto::scc_info_CatProfile.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:qqnews.CatProfile)
}
CatProfile::CatProfile(const CatProfile& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_type()) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  weight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_weight()) {
    weight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.weight_);
  }
  lv1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lv1()) {
    lv1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv1_);
  }
  lv2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lv2()) {
    lv2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv2_);
  }
  lv3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lv3()) {
    lv3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv3_);
  }
  lv4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lv4()) {
    lv4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv4_);
  }
  // @@protoc_insertion_point(copy_constructor:qqnews.CatProfile)
}

void CatProfile::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  weight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CatProfile::~CatProfile() {
  // @@protoc_insertion_point(destructor:qqnews.CatProfile)
  SharedDtor();
}

void CatProfile::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  weight_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lv4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CatProfile::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CatProfile::descriptor() {
  ::protobuf_profile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_profile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CatProfile& CatProfile::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_profile_2eproto::scc_info_CatProfile.base);
  return *internal_default_instance();
}


void CatProfile::Clear() {
// @@protoc_insertion_point(message_clear_start:qqnews.CatProfile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      type_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      weight_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      lv1_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      lv2_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      lv3_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000020u) {
      lv4_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CatProfile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qqnews.CatProfile)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string weight = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_weight()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->weight().data(), static_cast<int>(this->weight().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.weight");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string lv1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lv1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lv1().data(), static_cast<int>(this->lv1().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.lv1");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string lv2 = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lv2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lv2().data(), static_cast<int>(this->lv2().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.lv2");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string lv3 = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lv3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lv3().data(), static_cast<int>(this->lv3().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.lv3");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string lv4 = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lv4()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lv4().data(), static_cast<int>(this->lv4().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "qqnews.CatProfile.lv4");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qqnews.CatProfile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qqnews.CatProfile)
  return false;
#undef DO_
}

void CatProfile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qqnews.CatProfile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // optional string weight = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->weight().data(), static_cast<int>(this->weight().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.weight");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->weight(), output);
  }

  // optional string lv1 = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv1().data(), static_cast<int>(this->lv1().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->lv1(), output);
  }

  // optional string lv2 = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv2().data(), static_cast<int>(this->lv2().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->lv2(), output);
  }

  // optional string lv3 = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv3().data(), static_cast<int>(this->lv3().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->lv3(), output);
  }

  // optional string lv4 = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv4().data(), static_cast<int>(this->lv4().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->lv4(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:qqnews.CatProfile)
}

::google::protobuf::uint8* CatProfile::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qqnews.CatProfile)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // optional string weight = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->weight().data(), static_cast<int>(this->weight().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.weight");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->weight(), target);
  }

  // optional string lv1 = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv1().data(), static_cast<int>(this->lv1().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->lv1(), target);
  }

  // optional string lv2 = 4;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv2().data(), static_cast<int>(this->lv2().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->lv2(), target);
  }

  // optional string lv3 = 5;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv3().data(), static_cast<int>(this->lv3().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->lv3(), target);
  }

  // optional string lv4 = 6;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lv4().data(), static_cast<int>(this->lv4().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "qqnews.CatProfile.lv4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->lv4(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qqnews.CatProfile)
  return target;
}

size_t CatProfile::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qqnews.CatProfile)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 63u) {
    // optional string type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type());
    }

    // optional string weight = 2;
    if (has_weight()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->weight());
    }

    // optional string lv1 = 3;
    if (has_lv1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->lv1());
    }

    // optional string lv2 = 4;
    if (has_lv2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->lv2());
    }

    // optional string lv3 = 5;
    if (has_lv3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->lv3());
    }

    // optional string lv4 = 6;
    if (has_lv4()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->lv4());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CatProfile::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qqnews.CatProfile)
  GOOGLE_DCHECK_NE(&from, this);
  const CatProfile* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CatProfile>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qqnews.CatProfile)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qqnews.CatProfile)
    MergeFrom(*source);
  }
}

void CatProfile::MergeFrom(const CatProfile& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qqnews.CatProfile)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_type();
      type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_weight();
      weight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.weight_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_lv1();
      lv1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv1_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_lv2();
      lv2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv2_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_lv3();
      lv3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv3_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_lv4();
      lv4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lv4_);
    }
  }
}

void CatProfile::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qqnews.CatProfile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CatProfile::CopyFrom(const CatProfile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qqnews.CatProfile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CatProfile::IsInitialized() const {
  return true;
}

void CatProfile::Swap(CatProfile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CatProfile::InternalSwap(CatProfile* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  weight_.Swap(&other->weight_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lv1_.Swap(&other->lv1_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lv2_.Swap(&other->lv2_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lv3_.Swap(&other->lv3_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  lv4_.Swap(&other->lv4_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CatProfile::GetMetadata() const {
  protobuf_profile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_profile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void KBUserInfo::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int KBUserInfo::kCatProfileFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

KBUserInfo::KBUserInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_profile_2eproto::scc_info_KBUserInfo.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:qqnews.KBUserInfo)
}
KBUserInfo::KBUserInfo(const KBUserInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      cat_profile_(from.cat_profile_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:qqnews.KBUserInfo)
}

void KBUserInfo::SharedCtor() {
}

KBUserInfo::~KBUserInfo() {
  // @@protoc_insertion_point(destructor:qqnews.KBUserInfo)
  SharedDtor();
}

void KBUserInfo::SharedDtor() {
}

void KBUserInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* KBUserInfo::descriptor() {
  ::protobuf_profile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_profile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const KBUserInfo& KBUserInfo::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_profile_2eproto::scc_info_KBUserInfo.base);
  return *internal_default_instance();
}


void KBUserInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:qqnews.KBUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cat_profile_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool KBUserInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qqnews.KBUserInfo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .qqnews.CatProfile cat_profile = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_cat_profile()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qqnews.KBUserInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qqnews.KBUserInfo)
  return false;
#undef DO_
}

void KBUserInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qqnews.KBUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .qqnews.CatProfile cat_profile = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cat_profile_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->cat_profile(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:qqnews.KBUserInfo)
}

::google::protobuf::uint8* KBUserInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qqnews.KBUserInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .qqnews.CatProfile cat_profile = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->cat_profile_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->cat_profile(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qqnews.KBUserInfo)
  return target;
}

size_t KBUserInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qqnews.KBUserInfo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .qqnews.CatProfile cat_profile = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->cat_profile_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->cat_profile(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void KBUserInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qqnews.KBUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const KBUserInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const KBUserInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qqnews.KBUserInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qqnews.KBUserInfo)
    MergeFrom(*source);
  }
}

void KBUserInfo::MergeFrom(const KBUserInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qqnews.KBUserInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cat_profile_.MergeFrom(from.cat_profile_);
}

void KBUserInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qqnews.KBUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KBUserInfo::CopyFrom(const KBUserInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qqnews.KBUserInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KBUserInfo::IsInitialized() const {
  return true;
}

void KBUserInfo::Swap(KBUserInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void KBUserInfo::InternalSwap(KBUserInfo* other) {
  using std::swap;
  CastToBase(&cat_profile_)->InternalSwap(CastToBase(&other->cat_profile_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata KBUserInfo::GetMetadata() const {
  protobuf_profile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_profile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace qqnews
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::qqnews::CatProfile* Arena::CreateMaybeMessage< ::qqnews::CatProfile >(Arena* arena) {
  return Arena::CreateInternal< ::qqnews::CatProfile >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::qqnews::KBUserInfo* Arena::CreateMaybeMessage< ::qqnews::KBUserInfo >(Arena* arena) {
  return Arena::CreateInternal< ::qqnews::KBUserInfo >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
